# values-loan-service.yaml
nameOverride: loan-service
fullnameOverride: loan-service

image:
  repository: # <account>.dkr.ecr.<region>.amazonaws.com/loan-service
  tag: latest

containerPort: 8090
managementPort: 8091

service:
  type: ClusterIP
  port: 80
  targetPort: 8090

database:
  enabled: true
  host: ""    # loan-db.xxxx.us-east-1.rds.amazonaws.com
  port: 5432
  name: loan_db
  username: postgres
  existingSecret: "loan-service-db-secret"
  secretKey: "db-password"

kafka:
  enabled: false

replicaCount: 2
autoscaling:
  minReplicas: 2
  maxReplicas: 6

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"
